import { Inter } from "next/font/google";
import "./globals.css";
import CursorEffect from "@/components/CursorEffect/CursorEffect";
import StarsBackground from "@/components/StarsBackground/StarsBackground";

// Google Font (Inter)
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "HeyFynix - A Creative Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${inter.variable} font-sans antialiased`}suppressHydrationWarning={true}>
        {/* 👇 This makes the hover canvas global (on all pages) */}
        <StarsBackground />
        <CursorEffect />

        {/* 👇 Your actual website content */}
        {children}
      </body>
    </html>
  );
}
